name: Check With Clang Tidy

on:
    push:
        branches: ["main"]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: Clang-Tidy Test
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: "0"

            - name: Setup Clang Tidy
              run: |
                  sudo apt-get update
                  sudo apt-get install lsb-release wget software-properties-common gnupg -y
                  sudo wget https://apt.llvm.org/llvm.sh
                  sudo chmod +x llvm.sh
                  sudo ./llvm.sh 17
                  sudo rm llvm.sh
                  sudo apt-get update
                  sudo apt-get install clang-17 clang-tidy-17 python3 python3-pip ninja-build pkg-config -y

            - name: Setup Meson and Compilation database
              run: |
                  export CC=clang-17
                  export CXX=clang++-17
                  pip install meson
                  meson setup build

            - name: Check With Clang Tidy
              run: |
                  find src/ -iname *.cpp ! -iname *dayxx.cpp -exec clang-tidy-17 -p build {} +
